name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.2.3
publish_to: "none"


dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: git@github.com:FranciscoRdz2001/flutter_cache_manager.git
      ref: 5ba89c6b3f7f9dee60981e609d8e773ebeee1c6a
      path: flutter_cache_manager
  octo_image: ^1.0.0
  cached_network_image_platform_interface:
    path: ../cached_network_image_platform_interface


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  flutter_lints: ^1.0.4
  file: ^6.1.0

environment:
  flutter: ">=3.3.0"
  sdk: ">=2.18.0 <3.0.0"
